version: '3.8'

services:
  servicebox-app:
    build: .
    container_name: servicebox-app
    restart: always # Restarts automatically on failure or massive timeout crashes
    ports:
      - "8005:8005"
    depends_on:
      - redis
    networks:
      - default
      - caddy
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "3"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8005/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      caddy: servicebox.autoleeb.at
      caddy.reverse_proxy: "{{upstreams 8005}}"
    volumes:
      # Configurations, Database, Logs, and Downloads as Persistent Named Volumes
      - sb_config_data:/app/config
      - sb_app_data:/app/data
      - sb_logs_data:/app/logs
      - sb_downloads_data:/app/downloads
      - sb_debug_data:/app/debug
    environment:
      # Optional: Hier koennen Config-Werte ueberschrieben werden.
      - REDIS_URL=redis://redis:6379/0
      - DB_CONNECTION=sqlite:////app/data/servicebox_history.db
      - TZ=Europe/Vienna

  redis:
    image: redis:alpine
    container_name: servicebox-redis
    restart: always
    networks:
      - default
    volumes:
      - sb_redis_data:/data
    command: redis-server --appendonly yes

networks:
  default:
  caddy:
    external: true

volumes:
  sb_config_data:
  sb_app_data:
  sb_logs_data:
  sb_downloads_data:
  sb_debug_data:
  sb_redis_data:
