version: '3.8'

services:
  servicebox-app:
    build: .
    image: servicebox-app:1.0.1
    container_name: servicebox-app
    restart: always # Restarts automatically on failure or massive timeout crashes
    ports:
      - "8005:8005"
    depends_on:
      - redis
    networks:
      - default
      - caddy
    labels:
      caddy: servicebox.autoleeb.at
      caddy.reverse_proxy: "{{upstreams 8005}}"
    volumes:
      # Wir speichern die Datenbank in einem echten, sicheren Docker Volume
      - servicebox_db:/app/data
      - ./downloads:/app/downloads
      - ./debug:/app/debug
    environment:
      # Optional: Hier koennen Config-Werte ueberschrieben werden.
      - REDIS_URL=redis://redis:6379/0
      - DB_CONNECTION=sqlite:////app/data/servicebox_history.db

  redis:
    image: redis:alpine
    container_name: servicebox-redis
    restart: always
    networks:
      - default
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  default:
  caddy:
    external: true

volumes:
  redis_data:
  servicebox_db:
